// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportCourtManagent_Server.Models;

#nullable disable

namespace SportCourtManagent_Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportCourtManagent_Server.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("CourtId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("SlotId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.BookingService", b =>
                {
                    b.Property<int>("BookingServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingServiceId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookingServiceId");

                    b.HasIndex("BookingId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BookingServices");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.CoachSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("CoachId");

                    b.HasIndex("CourtId");

                    b.HasIndex("SlotId");

                    b.ToTable("CoachSchedules");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.ComplexCourtTypeService", b =>
                {
                    b.Property<int>("OfferingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferingId"));

                    b.Property<int>("ComplexId")
                        .HasColumnType("int");

                    b.Property<int>("CourtTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceMode")
                        .HasColumnType("int");

                    b.Property<int>("StockQty")
                        .HasColumnType("int");

                    b.HasKey("OfferingId");

                    b.HasIndex("CourtTypeId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ComplexId", "CourtTypeId", "ServiceId")
                        .IsUnique();

                    b.ToTable("ComplexCourtTypeServices");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Court", b =>
                {
                    b.Property<int>("CourtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourtId"));

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time");

                    b.Property<int>("ComplexId")
                        .HasColumnType("int");

                    b.Property<string>("CourtCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CourtSize")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CourtTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CourtId");

                    b.HasIndex("ComplexId");

                    b.HasIndex("CourtCode")
                        .IsUnique();

                    b.HasIndex("CourtTypeId");

                    b.ToTable("Courts");

                    b.HasData(
                        new
                        {
                            CourtId = 1,
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            ComplexId = 1,
                            CourtCode = "PB-P1",
                            CourtName = "Sân Pickleball P1",
                            CourtSize = "20x44 feet",
                            CourtTypeId = 1,
                            IsDeleted = false,
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            PricePerHour = 150000.00m,
                            Status = 0
                        },
                        new
                        {
                            CourtId = 2,
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            ComplexId = 1,
                            CourtCode = "BM-B1",
                            CourtName = "Sân Cầu Lông B1",
                            CourtSize = "6.1x13.4 meters",
                            CourtTypeId = 2,
                            IsDeleted = false,
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            PricePerHour = 100000.00m,
                            Status = 0
                        },
                        new
                        {
                            CourtId = 3,
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            ComplexId = 1,
                            CourtCode = "FB-F1",
                            CourtName = "Sân Bóng Đá F1",
                            CourtSize = "5-a-side",
                            CourtTypeId = 3,
                            IsDeleted = false,
                            OpenTime = new TimeSpan(0, 6, 0, 0, 0),
                            PricePerHour = 300000.00m,
                            Status = 0
                        });
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.CourtComplex", b =>
                {
                    b.Property<int>("ComplexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplexId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ComplexName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.HasKey("ComplexId");

                    b.HasIndex("ManagerId");

                    b.ToTable("CourtComplexes");

                    b.HasData(
                        new
                        {
                            ComplexId = 1,
                            Address = "Dịch Vọng, Cầu Giấy, Hà Nội",
                            ComplexName = "Tổ hợp thể thao Cầu Giấy",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tổ hợp thể thao hiện đại bậc nhất khu vực Cầu Giấy với nhiều loại sân khác nhau.",
                            ImageUrl = "https://example.com/complex1.jpg",
                            IsDeleted = false,
                            ManagerId = 2
                        });
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.CourtImage", b =>
                {
                    b.Property<int>("CourtImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourtImageId"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("CourtImageId");

                    b.HasIndex("CourtId");

                    b.ToTable("CourtImages");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.CourtPricing", b =>
                {
                    b.Property<int>("PricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PricingId"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.HasKey("PricingId");

                    b.HasIndex("CourtId");

                    b.HasIndex("SlotId");

                    b.ToTable("CourtPricing");

                    b.HasData(
                        new
                        {
                            PricingId = 1,
                            CourtId = 1,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 120000.00m,
                            SlotId = 1
                        },
                        new
                        {
                            PricingId = 2,
                            CourtId = 1,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 120000.00m,
                            SlotId = 2
                        },
                        new
                        {
                            PricingId = 3,
                            CourtId = 1,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 120000.00m,
                            SlotId = 3
                        },
                        new
                        {
                            PricingId = 4,
                            CourtId = 1,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 150000.00m,
                            SlotId = 4
                        },
                        new
                        {
                            PricingId = 5,
                            CourtId = 1,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 150000.00m,
                            SlotId = 5
                        },
                        new
                        {
                            PricingId = 6,
                            CourtId = 1,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 180000.00m,
                            SlotId = 6
                        },
                        new
                        {
                            PricingId = 7,
                            CourtId = 1,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 180000.00m,
                            SlotId = 7
                        },
                        new
                        {
                            PricingId = 8,
                            CourtId = 1,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 180000.00m,
                            SlotId = 8
                        },
                        new
                        {
                            PricingId = 9,
                            CourtId = 2,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 80000.00m,
                            SlotId = 1
                        },
                        new
                        {
                            PricingId = 10,
                            CourtId = 2,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 80000.00m,
                            SlotId = 2
                        },
                        new
                        {
                            PricingId = 11,
                            CourtId = 2,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 80000.00m,
                            SlotId = 3
                        },
                        new
                        {
                            PricingId = 12,
                            CourtId = 2,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 100000.00m,
                            SlotId = 4
                        },
                        new
                        {
                            PricingId = 13,
                            CourtId = 2,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 100000.00m,
                            SlotId = 5
                        },
                        new
                        {
                            PricingId = 14,
                            CourtId = 2,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 120000.00m,
                            SlotId = 6
                        },
                        new
                        {
                            PricingId = 15,
                            CourtId = 2,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 120000.00m,
                            SlotId = 7
                        },
                        new
                        {
                            PricingId = 16,
                            CourtId = 2,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 120000.00m,
                            SlotId = 8
                        });
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.CourtType", b =>
                {
                    b.Property<int>("CourtTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourtTypeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CourtTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("CourtTypes");

                    b.HasData(
                        new
                        {
                            CourtTypeId = 1,
                            IsActive = true,
                            TypeName = "Pickleball"
                        },
                        new
                        {
                            CourtTypeId = 2,
                            IsActive = true,
                            TypeName = "Badminton"
                        },
                        new
                        {
                            CourtTypeId = 3,
                            IsActive = true,
                            TypeName = "Football"
                        });
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.EquipmentInventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.HasIndex("ServiceId");

                    b.ToTable("EquipmentInventory");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEmailSent")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatPercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("PaymentId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.MaintenanceSchedule", b =>
                {
                    b.Property<int>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceId"));

                    b.Property<int?>("AssignedStaffId")
                        .HasColumnType("int");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaintenanceType")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Result")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MaintenanceId");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("CourtId");

                    b.ToTable("MaintenanceSchedules");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.MembershipTier", b =>
                {
                    b.Property<int>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TierId"));

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinPoints")
                        .HasColumnType("int");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TierId");

                    b.ToTable("MembershipTiers");

                    b.HasData(
                        new
                        {
                            TierId = 1,
                            DiscountPercent = 0.00m,
                            MinPoints = 0,
                            TierName = "Bronze"
                        },
                        new
                        {
                            TierId = 2,
                            DiscountPercent = 5.00m,
                            MinPoints = 100,
                            TierName = "Silver"
                        },
                        new
                        {
                            TierId = 3,
                            DiscountPercent = 10.00m,
                            MinPoints = 500,
                            TierName = "Gold"
                        });
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.PlayerRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("GenderPref")
                        .HasColumnType("int");

                    b.Property<int>("HostUserId")
                        .HasColumnType("int");

                    b.Property<int>("RequiredPlayers")
                        .HasColumnType("int");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("BookingId");

                    b.HasIndex("HostUserId");

                    b.ToTable("PlayerRequests");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.PlayerRequestMember", b =>
                {
                    b.Property<int>("PlayerRequestMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerRequestMemberId"));

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PlayerRequestMemberId");

                    b.HasIndex("UserId");

                    b.HasIndex("RequestId", "UserId")
                        .IsUnique();

                    b.ToTable("PlayerRequestMembers");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromoCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PromoName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("PromotionId");

                    b.HasIndex("PromoCode")
                        .IsUnique();

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.RecurringBooking", b =>
                {
                    b.Property<int>("RecurringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecurringId"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RecurringId");

                    b.HasIndex("CourtId");

                    b.HasIndex("SlotId");

                    b.HasIndex("UserId");

                    b.ToTable("RecurringBookings");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("CourtId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "System Administrator",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Complex Manager",
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Staff member",
                            RoleName = "Staff"
                        },
                        new
                        {
                            RoleId = 4,
                            Description = "End Customer",
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockQty")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            Category = "EquipmentRent",
                            CreatedAt = new DateTime(2026, 7, 5, 14, 54, 31, 110, DateTimeKind.Utc).AddTicks(7482),
                            IsActive = true,
                            Price = 30000.00m,
                            ServiceName = "Thuê vợt Pickleball",
                            StockQty = 20,
                            Unit = "cái"
                        },
                        new
                        {
                            ServiceId = 2,
                            Category = "EquipmentRent",
                            CreatedAt = new DateTime(2026, 7, 5, 14, 54, 31, 110, DateTimeKind.Utc).AddTicks(7489),
                            IsActive = true,
                            Price = 20000.00m,
                            ServiceName = "Thuê vợt cầu lông",
                            StockQty = 30,
                            Unit = "cái"
                        },
                        new
                        {
                            ServiceId = 3,
                            Category = "Drink",
                            CreatedAt = new DateTime(2026, 7, 5, 14, 54, 31, 110, DateTimeKind.Utc).AddTicks(7491),
                            IsActive = true,
                            Price = 15000.00m,
                            ServiceName = "Nước uống Pocari",
                            StockQty = 100,
                            Unit = "cái"
                        },
                        new
                        {
                            ServiceId = 4,
                            Category = "Drink",
                            CreatedAt = new DateTime(2026, 7, 5, 14, 54, 31, 110, DateTimeKind.Utc).AddTicks(7493),
                            IsActive = true,
                            Price = 10000.00m,
                            ServiceName = "Nước suối Aquafina",
                            StockQty = 150,
                            Unit = "cái"
                        });
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.StaffComplex", b =>
                {
                    b.Property<int>("StaffComplexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffComplexId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComplexId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("StaffComplexId");

                    b.HasIndex("ComplexId");

                    b.HasIndex("StaffId", "ComplexId")
                        .IsUnique();

                    b.ToTable("StaffComplexes");

                    b.HasData(
                        new
                        {
                            StaffComplexId = 1,
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ComplexId = 1,
                            StaffId = 3
                        });
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.StaffShift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComplexId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<int>("ShiftType")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftId");

                    b.HasIndex("ComplexId", "ShiftDate");

                    b.HasIndex("StaffId", "ShiftDate", "ShiftType")
                        .IsUnique();

                    b.ToTable("StaffShifts");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.TaskItem", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("AssignedStaffId")
                        .HasColumnType("int");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComplexId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("BookingId");

                    b.HasIndex("ComplexId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.TimeSlot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<int>("DayType")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("SlotId");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            SlotId = 1,
                            DayType = 0,
                            EndTime = new TimeSpan(0, 7, 30, 0, 0),
                            SlotName = "Slot 1 (06:00 - 07:30)",
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            SlotId = 2,
                            DayType = 0,
                            EndTime = new TimeSpan(0, 9, 0, 0, 0),
                            SlotName = "Slot 2 (07:30 - 09:00)",
                            StartTime = new TimeSpan(0, 7, 30, 0, 0)
                        },
                        new
                        {
                            SlotId = 3,
                            DayType = 0,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            SlotName = "Slot 3 (09:00 - 10:30)",
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            SlotId = 4,
                            DayType = 0,
                            EndTime = new TimeSpan(0, 16, 30, 0, 0),
                            SlotName = "Slot 4 (15:00 - 16:30)",
                            StartTime = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            SlotId = 5,
                            DayType = 0,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            SlotName = "Slot 5 (16:30 - 18:00)",
                            StartTime = new TimeSpan(0, 16, 30, 0, 0)
                        },
                        new
                        {
                            SlotId = 6,
                            DayType = 0,
                            EndTime = new TimeSpan(0, 19, 30, 0, 0),
                            SlotName = "Slot 6 (18:00 - 19:30)",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            SlotId = 7,
                            DayType = 0,
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            SlotName = "Slot 7 (19:30 - 21:00)",
                            StartTime = new TimeSpan(0, 19, 30, 0, 0)
                        },
                        new
                        {
                            SlotId = 8,
                            DayType = 0,
                            EndTime = new TimeSpan(0, 22, 30, 0, 0),
                            SlotName = "Slot 8 (21:00 - 22:30)",
                            StartTime = new TimeSpan(0, 21, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TournamentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TournamentId");

                    b.HasIndex("UserId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<int?>("MembershipTierId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MembershipTierId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@sportcourt.com",
                            FullName = "System Administrator",
                            Gender = 2,
                            IsActive = true,
                            LoyaltyPoints = 0,
                            PasswordHash = "$2a$11$qR3gWwH8wF6hKqU6sXn9O.H2QJ1WJ5tQ.z5eJjU5tK8l8tS8z8z8z",
                            Phone = "0987654321",
                            SkillLevel = 2
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manager@sportcourt.com",
                            FullName = "Complex Manager",
                            Gender = 0,
                            IsActive = true,
                            LoyaltyPoints = 0,
                            PasswordHash = "$2a$11$qR3gWwH8wF6hKqU6sXn9O.H2QJ1WJ5tQ.z5eJjU5tK8l8tS8z8z8z",
                            Phone = "0987654322",
                            SkillLevel = 1
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff@sportcourt.com",
                            FullName = "Staff Member",
                            Gender = 1,
                            IsActive = true,
                            LoyaltyPoints = 0,
                            PasswordHash = "$2a$11$qR3gWwH8wF6hKqU6sXn9O.H2QJ1WJ5tQ.z5eJjU5tK8l8tS8z8z8z",
                            Phone = "0987654323",
                            SkillLevel = 0
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer@sportcourt.com",
                            FullName = "John Doe",
                            Gender = 2,
                            IsActive = true,
                            LoyaltyPoints = 50,
                            MembershipTierId = 1,
                            PasswordHash = "$2a$11$qR3gWwH8wF6hKqU6sXn9O.H2QJ1WJ5tQ.z5eJjU5tK8l8tS8z8z8z",
                            Phone = "0987654324",
                            SkillLevel = 0
                        });
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleId = 1,
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            UserRoleId = 2,
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            UserRoleId = 3,
                            RoleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            UserRoleId = 4,
                            RoleId = 4,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Waitlist", b =>
                {
                    b.Property<int>("WaitlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WaitlistId"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WaitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WaitlistId");

                    b.HasIndex("CourtId");

                    b.HasIndex("SlotId");

                    b.HasIndex("UserId");

                    b.ToTable("Waitlists");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.AuditLog", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Booking", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.Court", "Court")
                        .WithMany("Bookings")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.Promotion", "Promotion")
                        .WithMany("Bookings")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportCourtManagent_Server.Models.TimeSlot", "TimeSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.Tournament", "Tournament")
                        .WithMany("Bookings")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SportCourtManagent_Server.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Promotion");

                    b.Navigation("TimeSlot");

                    b.Navigation("Tournament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.BookingService", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.Booking", "Booking")
                        .WithMany("BookingServices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.Service", "Service")
                        .WithMany("BookingServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.CoachSchedule", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.User", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.Court", "Court")
                        .WithMany("CoachSchedules")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.TimeSlot", "TimeSlot")
                        .WithMany("CoachSchedules")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Court");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.ComplexCourtTypeService", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.CourtComplex", "Complex")
                        .WithMany()
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.CourtType", "CourtType")
                        .WithMany()
                        .HasForeignKey("CourtTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.Service", "Service")
                        .WithMany("ComplexCourtTypeServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complex");

                    b.Navigation("CourtType");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Court", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.CourtComplex", "Complex")
                        .WithMany("Courts")
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.CourtType", "CourtType")
                        .WithMany("Courts")
                        .HasForeignKey("CourtTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complex");

                    b.Navigation("CourtType");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.CourtComplex", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.User", "Manager")
                        .WithMany("ManagedComplexes")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.CourtImage", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.Court", "Court")
                        .WithMany("CourtImages")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.CourtPricing", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.Court", "Court")
                        .WithMany("CourtPricings")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.TimeSlot", "TimeSlot")
                        .WithMany("CourtPricings")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.EquipmentInventory", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.Service", "Service")
                        .WithMany("EquipmentInventories")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Invoice", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.Booking", "Booking")
                        .WithOne("Invoice")
                        .HasForeignKey("SportCourtManagent_Server.Models.Invoice", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.Payment", "Payment")
                        .WithMany("Invoices")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.MaintenanceSchedule", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.User", "AssignedStaff")
                        .WithMany()
                        .HasForeignKey("AssignedStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportCourtManagent_Server.Models.Court", "Court")
                        .WithMany("MaintenanceSchedules")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedStaff");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Notification", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Payment", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("SportCourtManagent_Server.Models.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.PlayerRequest", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.Booking", "Booking")
                        .WithMany("PlayerRequests")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.User", "HostUser")
                        .WithMany("PlayerRequests")
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("HostUser");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.PlayerRequestMember", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.PlayerRequest", "PlayerRequest")
                        .WithMany("PlayerRequestMembers")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.User", "User")
                        .WithMany("PlayerRequestMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.RecurringBooking", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.Court", "Court")
                        .WithMany("RecurringBookings")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.TimeSlot", "TimeSlot")
                        .WithMany("RecurringBookings")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.User", "User")
                        .WithMany("RecurringBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("TimeSlot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Review", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("SportCourtManagent_Server.Models.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.Court", "Court")
                        .WithMany("Reviews")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Court");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.StaffComplex", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.CourtComplex", "Complex")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.User", "Staff")
                        .WithMany("ComplexAssignments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complex");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.StaffShift", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.CourtComplex", "Complex")
                        .WithMany("StaffShifts")
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.User", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complex");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.TaskItem", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.User", "AssignedStaff")
                        .WithMany("TasksAssigned")
                        .HasForeignKey("AssignedStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportCourtManagent_Server.Models.Booking", "Booking")
                        .WithMany("Tasks")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportCourtManagent_Server.Models.CourtComplex", "Complex")
                        .WithMany("Tasks")
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.User", "CreatedBy")
                        .WithMany("TasksCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedStaff");

                    b.Navigation("Booking");

                    b.Navigation("Complex");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Tournament", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.User", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.MembershipTier", "MembershipTier")
                        .WithMany("Users")
                        .HasForeignKey("MembershipTierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MembershipTier");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.UserRole", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Waitlist", b =>
                {
                    b.HasOne("SportCourtManagent_Server.Models.Court", "Court")
                        .WithMany("Waitlists")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.TimeSlot", "TimeSlot")
                        .WithMany("Waitlists")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportCourtManagent_Server.Models.User", "User")
                        .WithMany("Waitlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("TimeSlot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Booking", b =>
                {
                    b.Navigation("BookingServices");

                    b.Navigation("Invoice");

                    b.Navigation("Payment");

                    b.Navigation("PlayerRequests");

                    b.Navigation("Review");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Court", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CoachSchedules");

                    b.Navigation("CourtImages");

                    b.Navigation("CourtPricings");

                    b.Navigation("MaintenanceSchedules");

                    b.Navigation("RecurringBookings");

                    b.Navigation("Reviews");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.CourtComplex", b =>
                {
                    b.Navigation("Courts");

                    b.Navigation("StaffAssignments");

                    b.Navigation("StaffShifts");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.CourtType", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.MembershipTier", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Payment", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.PlayerRequest", b =>
                {
                    b.Navigation("PlayerRequestMembers");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Promotion", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Service", b =>
                {
                    b.Navigation("BookingServices");

                    b.Navigation("ComplexCourtTypeServices");

                    b.Navigation("EquipmentInventories");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.TimeSlot", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CoachSchedules");

                    b.Navigation("CourtPricings");

                    b.Navigation("RecurringBookings");

                    b.Navigation("Waitlists");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.Tournament", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SportCourtManagent_Server.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ComplexAssignments");

                    b.Navigation("ManagedComplexes");

                    b.Navigation("Notifications");

                    b.Navigation("PlayerRequestMembers");

                    b.Navigation("PlayerRequests");

                    b.Navigation("RecurringBookings");

                    b.Navigation("Reviews");

                    b.Navigation("TasksAssigned");

                    b.Navigation("TasksCreated");

                    b.Navigation("UserRoles");

                    b.Navigation("Waitlists");
                });
#pragma warning restore 612, 618
        }
    }
}
