using System.ComponentModel.DataAnnotations;
using SportCourtManagerment.Enums;

namespace SportCourtManagerment.Models;

/// <summary>Fixed recurring court schedule (e.g. every Mon/Wed/Fri).</summary>
public class RecurringBooking
{
  /// <summary>Primary key.</summary>
  public int RecurringId { get; set; }

  /// <summary>FK to the user who set up this schedule.</summary>
  public int UserId { get; set; }

  /// <summary>FK to the reserved court.</summary>
  public int CourtId { get; set; }

  /// <summary>FK to the time slot used each session.</summary>
  public int SlotId { get; set; }

  /// <summary>First date of the recurring schedule.</summary>
  public DateOnly StartDate { get; set; }

  /// <summary>Last date of the recurring schedule.</summary>
  public DateOnly EndDate { get; set; }

  /// <summary>Comma-separated day-of-week numbers, e.g. '1,3,5' = Mon/Wed/Fri.</summary>
  [Required, MaxLength(20)]
  public string DaysOfWeek { get; set; } = string.Empty;

  /// <summary>Session start time.</summary>
  public TimeOnly StartTime { get; set; }

  /// <summary>Session end time.</summary>
  public TimeOnly EndTime { get; set; }

  /// <summary>Total number of sessions generated by this schedule.</summary>
  public int TotalSessions { get; set; }

  /// <summary>Current schedule status.</summary>
  public RecurringBookingStatus Status { get; set; }

  /// <summary>Record creation timestamp.</summary>
  public DateTime CreatedAt { get; set; }

  // Navigation properties
  public User User { get; set; } = null!;
  public Court Court { get; set; } = null!;
  public TimeSlot TimeSlot { get; set; } = null!;
  public ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}
